[package]
name = "fibonacci"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint = "0.4.6"
thousands = "0.2.0"
wait-timeout = "0.2.1"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip = true
